# Generated by Django 4.0.2 on 2022-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
