# Generated by Django 4.0.5 on 2022-06-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('tipo', models.BooleanField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='juguete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('usado', models.BooleanField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
