# Generated by Django 4.0.5 on 2022-06-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_perros', '0002_alimento_imagen_juguete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='agregar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='alimentos')),
            ],
        ),
    ]
