# Generated by Django 4.0.5 on 2022-06-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_perros', '0003_agregar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregar',
            name='imagen',
        ),
    ]
