# Generated by Django 4.0.5 on 2022-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_perros', '0004_remove_agregar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='alimentos'),
        ),
    ]
